// swift-tools-version: 5.6

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "LetsCoding",
    platforms: [
        .iOS("15.2")
    ],
    products: [
        .iOSApplication(
            name: "LetsCoding",
            targets: ["AppModule"],
            bundleIdentifier: "xyz.wannabewize.example.LetsCoding",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .cloud),
            accentColor: .presetColor(.cyan),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        )
    ],
    dependencies: [
        .package(url: "https://github.com/willdale/SwiftUICharts.git", "2.0.0"..<"3.0.0")
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "SwiftUICharts", package: "swiftuicharts")
            ],
            path: ".",
            resources: [
                .process("Resources")
            ]
        )
    ]
)